---
- name: Deploy ReplicaSet MongoDB per tenant via MCK
  hosts: localhost
  gather_facts: false

  vars:
    k8s_context: "{{ kube_context | default(omit) }}"

  roles:
    - role: mck_deploy_replicaset